include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style Rules
    always_declare_return_types: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
    # Error Prevention
    use_build_context_synchronously: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    
    # Code Quality
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unnecessary_late: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "flutter/**"
  
  errors:
    invalid_annotation_target: ignore